services:
  - type: web
    name: sms-bulk
    env: node
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium-browser && \
      npm ci
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: NODE_ENV
        value: production
